package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type applyPatchTool struct{}

func ApplyPatch() Tool { return &applyPatchTool{} }

func (t *applyPatchTool) Name() string { return "apply_patch" }

func (t *applyPatchTool) Description() string {
	return "Apply a unified diff patch to files. Parses patch hunks and makes targeted text replacements. Use this for applying code changes generated by other tools."
}

func (t *applyPatchTool) InputSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"patch_text": map[string]any{"type": "string", "description": "The unified diff patch text to apply."},
		},
		"required": []string{"patch_text"},
	}
}

func (t *applyPatchTool) Execute(ctx context.Context, call Context, input json.RawMessage) Result {
	var p struct {
		PatchText string `json:"patch_text"`
	}
	if err := json.Unmarshal(input, &p); err != nil {
		return Result{Output: "error: " + err.Error(), IsError: true}
	}
	p.PatchText = strings.TrimSpace(p.PatchText)
	if p.PatchText == "" {
		return Result{Output: "error: patch_text is required", IsError: true}
	}

	hunks := parseUnifiedDiff(p.PatchText)
	if len(hunks) == 0 {
		return Result{Output: "error: no valid hunks found in patch", IsError: true}
	}

	var results []string
	for _, hunk := range hunks {
		if hunk.FilePath == "" {
			results = append(results, "error: hunk missing file path")
			continue
		}

		// Read the target file
		absPath := hunk.FilePath
		if !filepath.IsAbs(absPath) {
			absPath = filepath.Join(cwd(), hunk.FilePath)
		}

		content, err := os.ReadFile(absPath)
		if err != nil {
			results = append(results, fmt.Sprintf("error reading %s: %v", hunk.FilePath, err))
			continue
		}

		oldStr := strings.TrimSpace(hunk.OldText)
		newStr := strings.TrimSpace(hunk.NewText)
		fileContent := string(content)

		if !strings.Contains(fileContent, oldStr) {
			results = append(results, fmt.Sprintf("error: could not find match in %s", hunk.FilePath))
			continue
		}

		updated := strings.Replace(fileContent, oldStr, newStr, 1)
		if err := os.WriteFile(absPath, []byte(updated), 0644); err != nil {
			results = append(results, fmt.Sprintf("error writing %s: %v", hunk.FilePath, err))
			continue
		}
		results = append(results, fmt.Sprintf("applied patch to %s", hunk.FilePath))
	}

	return Result{
		Title:  fmt.Sprintf("Patch applied to %d file(s)", len(results)),
		Output: strings.Join(results, "\n"),
	}
}

type patchHunk struct {
	FilePath string
	OldText  string
	NewText  string
}

func parseUnifiedDiff(diff string) []patchHunk {
	var hunks []patchHunk
	lines := strings.Split(diff, "\n")

	var currentHunk *patchHunk
	var oldLines, newLines []string
	inHunk := false
	readingOld := false
	readingNew := false

	for _, line := range lines {
		if strings.HasPrefix(line, "--- ") {
			// File path for old file — skip
			continue
		}
		if after, ok := strings.CutPrefix(line, "+++ "); ok {
			path := strings.TrimSpace(after)
			// Strip a/ b/ prefixes
			path = strings.TrimPrefix(path, "b/")
			path = strings.TrimPrefix(path, "a/")
			if currentHunk != nil && (len(oldLines) > 0 || len(newLines) > 0) {
				currentHunk.OldText = strings.Join(oldLines, "\n")
				currentHunk.NewText = strings.Join(newLines, "\n")
				hunks = append(hunks, *currentHunk)
			}
			currentHunk = &patchHunk{FilePath: path}
			oldLines = nil
			newLines = nil
			inHunk = false
			continue
		}
		if strings.HasPrefix(line, "@@") {
			if currentHunk != nil && (len(oldLines) > 0 || len(newLines) > 0) {
				currentHunk.OldText = strings.Join(oldLines, "\n")
				currentHunk.NewText = strings.Join(newLines, "\n")
				hunks = append(hunks, *currentHunk)
			}
			oldLines = nil
			newLines = nil
			inHunk = true
			continue
		}
		if !inHunk || currentHunk == nil {
			continue
		}

		if oldLine, ok := strings.CutPrefix(line, "-"); ok && !strings.HasPrefix(line, "---") {
			oldLines = append(oldLines, oldLine)
			readingOld = true
		} else if newLine, ok := strings.CutPrefix(line, "+"); ok {
			newLines = append(newLines, newLine)
			readingNew = true
		} else if strings.HasPrefix(line, " ") {
			if readingOld || readingNew {
				oldLines = append(oldLines, line[1:])
				newLines = append(newLines, line[1:])
			}
		}
	}

	// Last hunk
	if currentHunk != nil && (len(oldLines) > 0 || len(newLines) > 0) {
		currentHunk.OldText = strings.Join(oldLines, "\n")
		currentHunk.NewText = strings.Join(newLines, "\n")
		hunks = append(hunks, *currentHunk)
	}

	return hunks
}

func cwd() string {
	dir, _ := os.Getwd()
	return dir
}
